name: Linux

on:
  pull_request:
  push:
    branches:
      - master
    paths:
    - '.github/workflows/linux.yml'
    - 'backend/**/*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update dependencies
      working-directory: ./backend
      run: sudo apt-get install libgtk-3-dev && cargo update
    - name: Build
      working-directory: ./backend
      run: cargo build --release --verbose
