name: Release for branch

on:
  workflow_dispatch:
    inputs:
      json:
        description: 'json'
        required: true
        default: 'release'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get version from file
      id: cargo_version
      run: 
        version=$(cat backend/Cargo.toml | grep version | head -n1);
        version=${version//[*version| |=|\"]};
        sed -i 's/release.json/${{ github.event.inputs.json }}.json/' src/*;
        echo '::set-output name=version::'${version};
        
    - run: cargo install cross

    - name: build
      run: cd backend && cross build --target=i686-pc-windows-gnu --release

    - name: Package Files
      id: package
      shell: bash
      run: >
        cp ./backend/target/i686-pc-windows-gnu/release/renegade-x-launcher.exe "./Renegade X Launcher.exe";
        zip -j9 RenX-Launcher "Renegade X Launcher.exe" "RenegadeX-folder-permissions.exe" "sciter.dll" "SelfUpdateExecutor.exe";
        zip -9 RenX-Launcher -r "dom";
        echo '::set-output name=hash::'$(sha256sum RenX-Launcher.zip | awk '{print toupper($1)}');

    - name: Upload ftp
      uses: bayssmekanique/action-simple-file-upload@v1
      with:
        host: ${{ secrets.FTP_URL }}
        user: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        src: RenX-Launcher.zip
        dest: RenX-Launcher-${{ steps.cargo_version.outputs.version }}-${{ github.event.inputs.json }}.zip

    - name: Update version file
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: >
         echo "$(jq '.launcher={"version_name":"${{ steps.cargo_version.outputs.version }}","version_number":(.launcher.version_number + 1),"patch_url":"https://renxdownloads.b-cdn.net/RenX-Launcher-${{ steps.cargo_version.outputs.version }}-${{ github.event.inputs.json }}.zip","patch_hash":"${{ steps.package.outputs.hash }}","banners_url":.launcher.banners_url}' static.renegade-x.com/data/launcher_data/version/${{ github.event.inputs.json }}.json)" > static.renegade-x.com/data/launcher_data/version/${{ github.event.inputs.json }}.json
        host: ${{ secrets.SSH_URL }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USERNAME }}
        privateKey: ${{ secrets.SSH_PRIVATE_KEY }}